"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var ContactBook_class_1 = require("./ContactBook-class");
var Contact_class_1 = require("./Contact-class");
var rolodex = new ContactBook_class_1.ContactBook();
var alan = new Contact_class_1.Contact('Alan', '333-333-3333');
var louie = new Contact_class_1.Contact('Le Roi', '999-999-9999');
rolodex.addContact(alan);
rolodex.addContact(louie);
rolodex.printContacts();
